<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6c3daab4-5575-4edc-b010-27078c8eb2aa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiftVeil.Application\RiftVeil.Application.csproj" />
    <ProjectReference Include="..\RiftVeil.Domain\RiftVeil.Domain.csproj" />
    <ProjectReference Include="..\RiftVeil.Infrastructure\RiftVeil.Infrastructure.csproj" />
  </ItemGroup>

</Project>
